[build]
  functions = "functions"
  publish = "build/"
[[redirects]]
  from = "/wallpaper/*"
  to = "/.netlify/functions/wallpaper/:splat"
  status = 200
[[redirects]]
  from = "/"
  to = "/popup.html"
  status = 200
[[headers]]
  for = "/*"
    [headers.values]
      Cache-Control = "no-cache"
[build]
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF config functions public src"