name: Daily Sync

on:
  schedule:
    - cron: "0 12 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Run sync script
        run: node sync.js

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git fetch origin master
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated sync"
          git push
